"""First migration

Revision ID: 5fc98ea52342
Revises: bc22294479e6
Create Date: 2023-05-23 18:09:14.339334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc98ea52342'
down_revision = 'bc22294479e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
